// The theme's chrome, in the site's language.
//
// `archiveText` covers the words around a post and a listing. This covers the
// rest of what the theme itself says: the search box, the menus, the slider
// and modal controls, the comment form. All of it was written in English on
// every site — an Arabic blog asked for "Your comment" under an Arabic heading
// and told a screen reader "Open menu", "Back to top", "Next slide".
//
// Two tables rather than one because they are two vocabularies, and because
// `archiveText` is built from a positional constructor that is already at 21
// arguments; adding twenty more would make a silent off-by-one inevitable.
// This one is keyed, so a missing or misplaced string is a type error.
//
// Same rule as the other tables: the languages the picker offers most often,
// English for everything else.

import { counted, type PluralForms } from "./plural";

export interface UiText {
  /* Search — the header box, the sidebar widget and the results page. */
  search: string;
  searchPlaceholder: string;
  openSearch: string;
  closeSearch: string;
  /** The results heading. The quotes are part of the wording, so each
   *  language brings the pair it actually uses. */
  searchResultsFor: (query: string) => string;
  noResults: string;

  /* Header and page chrome. */
  openMenu: string;
  menu: string;
  closeMenu: string;
  language: string;
  backToTop: string;
  toggleDarkMode: string;
  toggleToc: string;
  close: string;
  map: string;

  /* Slider. `carousel` and `slide` are aria-roledescription, which the spec
     says must be in the language of the page, not in English. */
  carousel: string;
  slide: string;
  prevSlide: string;
  nextSlide: string;
  /** Each slide's accessible name: "3 of 8". */
  slideOf: (i: number, total: number) => string;
  /** The play button on a lazy-loaded video placeholder. */
  playVideo: string;
  playVideoTitled: (title: string) => string;

  /** A countdown whose author never set an end date, and one that has passed. */
  offerEnded: string;

  /* Comments — the section heading, then the form. */
  leaveAComment: string;
  comments: (n: number) => string;
  yourName: string;
  yourEmail: string;
  yourWebsite: string;
  yourComment: string;
  postComment: string;
  posting: string;
  commentPending: string;
  commentPosted: string;

  /* An author line with nothing to show. */
  postsBy: (name: string) => string;
  siteTeam: string;

  /* A countdown block whose date was never set. */
  noDateSet: string;
  /** The language key that matched — for `Intl` formatting in the same language. */
  lang: string;
  /** Business Info: a day with no opening hours. */
  closedLabel: string;
  /** Form validation. `{field}` is replaced with the field's label. */
  fieldRequired: string;
  invalidEmail: string;
  /** Default label on the contact form's submit button. */
  sendMessage: string;
  /** Comment reply controls. */
  reply: string;
  cancelReply: string;
  /** The first focusable thing on every page: jumps past the header. */
  skipToContent: string;
  /** The before/after slider's accessible name when the author set no labels. */
  compareImages: string;
  /** The slider's autoplay button (WCAG 2.2.2: moving content can be paused). */
  pauseSlides: string;
  playSlides: string;
}

/** A table row: the forms of "comment", not yet a function of `n`. */
type UiEntry = Omit<UiText, "comments" | "lang" | "skipToContent" | keyof MediaControls> & { commentForms: PluralForms };

type MediaControls = { compareImages: string; pauseSlides: string; playSlides: string };

/**
 * The image-compare and slideshow controls, added after the main table and
 * kept apart like SKIP_TO_CONTENT. A language missing here uses English.
 */
const MEDIA_CONTROLS: Record<string, MediaControls> = {
  en: { compareImages: "Compare the two images", pauseSlides: "Pause slideshow", playSlides: "Play slideshow" },
  ar: { compareImages: "قارن بين الصورتين", pauseSlides: "إيقاف العرض مؤقتًا", playSlides: "تشغيل العرض" },
  fr: { compareImages: "Comparer les deux images", pauseSlides: "Mettre le diaporama en pause", playSlides: "Lire le diaporama" },
  es: { compareImages: "Comparar las dos imágenes", pauseSlides: "Pausar la presentación", playSlides: "Reproducir la presentación" },
  pt: { compareImages: "Comparar as duas imagens", pauseSlides: "Pausar apresentação", playSlides: "Reproduzir apresentação" },
  de: { compareImages: "Die beiden Bilder vergleichen", pauseSlides: "Diashow anhalten", playSlides: "Diashow abspielen" },
  it: { compareImages: "Confronta le due immagini", pauseSlides: "Metti in pausa la presentazione", playSlides: "Avvia la presentazione" },
  tr: { compareImages: "İki görseli karşılaştır", pauseSlides: "Slayt gösterisini duraklat", playSlides: "Slayt gösterisini oynat" },
  ru: { compareImages: "Сравнить два изображения", pauseSlides: "Приостановить слайд-шоу", playSlides: "Запустить слайд-шоу" },
  ur: { compareImages: "دونوں تصاویر کا موازنہ کریں", pauseSlides: "سلائیڈ شو روکیں", playSlides: "سلائیڈ شو چلائیں" },
  fa: { compareImages: "مقایسهٔ دو تصویر", pauseSlides: "توقف نمایش اسلاید", playSlides: "پخش نمایش اسلاید" },
  hi: { compareImages: "दोनों चित्रों की तुलना करें", pauseSlides: "स्लाइड शो रोकें", playSlides: "स्लाइड शो चलाएँ" },
  id: { compareImages: "Bandingkan kedua gambar", pauseSlides: "Jeda tayangan slide", playSlides: "Putar tayangan slide" },
  nl: { compareImages: "Vergelijk de twee afbeeldingen", pauseSlides: "Diavoorstelling pauzeren", playSlides: "Diavoorstelling afspelen" },
  pl: { compareImages: "Porównaj oba obrazy", pauseSlides: "Wstrzymaj pokaz slajdów", playSlides: "Odtwórz pokaz slajdów" },
  uk: { compareImages: "Порівняти два зображення", pauseSlides: "Призупинити слайд-шоу", playSlides: "Запустити слайд-шоу" },
  cs: { compareImages: "Porovnat oba obrázky", pauseSlides: "Pozastavit prezentaci", playSlides: "Spustit prezentaci" },
  el: { compareImages: "Σύγκριση των δύο εικόνων", pauseSlides: "Παύση προβολής διαφανειών", playSlides: "Αναπαραγωγή προβολής διαφανειών" },
  ro: { compareImages: "Compară cele două imagini", pauseSlides: "Întrerupe prezentarea", playSlides: "Pornește prezentarea" },
  hu: { compareImages: "A két kép összehasonlítása", pauseSlides: "Diavetítés szüneteltetése", playSlides: "Diavetítés lejátszása" },
  sv: { compareImages: "Jämför de två bilderna", pauseSlides: "Pausa bildspelet", playSlides: "Spela bildspelet" },
  da: { compareImages: "Sammenlign de to billeder", pauseSlides: "Sæt diasshowet på pause", playSlides: "Afspil diasshowet" },
  nb: { compareImages: "Sammenlign de to bildene", pauseSlides: "Sett lysbildefremvisningen på pause", playSlides: "Spill av lysbildefremvisningen" },
  fi: { compareImages: "Vertaa kahta kuvaa", pauseSlides: "Keskeytä diaesitys", playSlides: "Toista diaesitys" },
  he: { compareImages: "השוואה בין שתי התמונות", pauseSlides: "השהיית המצגת", playSlides: "הפעלת המצגת" },
  ja: { compareImages: "2つの画像を比較", pauseSlides: "スライドショーを一時停止", playSlides: "スライドショーを再生" },
  ko: { compareImages: "두 이미지 비교", pauseSlides: "슬라이드쇼 일시정지", playSlides: "슬라이드쇼 재생" },
  vi: { compareImages: "So sánh hai hình ảnh", pauseSlides: "Tạm dừng trình chiếu", playSlides: "Phát trình chiếu" },
  th: { compareImages: "เปรียบเทียบภาพทั้งสอง", pauseSlides: "หยุดสไลด์โชว์ชั่วคราว", playSlides: "เล่นสไลด์โชว์" },
  ms: { compareImages: "Bandingkan kedua-dua imej", pauseSlides: "Jeda tayangan slaid", playSlides: "Mainkan tayangan slaid" },
  bn: { compareImages: "দুটি ছবি তুলনা করুন", pauseSlides: "স্লাইডশো থামান", playSlides: "স্লাইডশো চালান" },
};

/**
 * "Skip to content", kept as its own table rather than a key in every entry
 * below: it was added after the others, and one table is one place to check.
 */
const SKIP_TO_CONTENT: Record<string, string> = {
  en: "Skip to content",
  ar: "تخطَّ إلى المحتوى",
  fr: "Aller au contenu",
  es: "Saltar al contenido",
  pt: "Pular para o conteúdo",
  de: "Zum Inhalt springen",
  it: "Vai al contenuto",
  tr: "İçeriğe geç",
  ru: "Перейти к содержимому",
  ur: "مواد پر جائیں",
  fa: "پرش به محتوا",
  hi: "सामग्री पर जाएँ",
  id: "Langsung ke konten",
  nl: "Naar de inhoud",
  pl: "Przejdź do treści",
  uk: "Перейти до вмісту",
  cs: "Přejít na obsah",
  el: "Μετάβαση στο περιεχόμενο",
  ro: "Salt la conținut",
  hu: "Ugrás a tartalomhoz",
  sv: "Hoppa till innehållet",
  da: "Spring til indhold",
  nb: "Hopp til innhold",
  fi: "Siirry sisältöön",
  he: "דלג לתוכן",
  ja: "コンテンツへスキップ",
  ko: "본문으로 건너뛰기",
  vi: "Chuyển đến nội dung",
  th: "ข้ามไปยังเนื้อหา",
  ms: "Langkau ke kandungan",
  fil: "Lumaktaw sa nilalaman",
  sw: "Ruka hadi maudhui",
  bn: "বিষয়বস্তুতে যান",
  ps: "منځپانګې ته ورشئ",
  pa: "ਸਮੱਗਰੀ 'ਤੇ ਜਾਓ",
  ta: "உள்ளடக்கத்திற்குச் செல்",
  te: "కంటెంట్‌కు వెళ్ళండి",
  mr: "मजकुराकडे जा",
  gu: "સામગ્રી પર જાઓ",
  kn: "ವಿಷಯಕ್ಕೆ ಹೋಗಿ",
  ml: "ഉള്ളടക്കത്തിലേക്ക് പോകുക",
  ne: "सामग्रीमा जानुहोस्",
  si: "අන්තර්ගතයට යන්න",
};

const TEXT: Record<string, UiEntry> = {
  en: {
    search: "Search", searchPlaceholder: "Search…", openSearch: "Open search",
    searchResultsFor: (q) => `Search results for “${q}”`,
    closeSearch: "Close search", noResults: "Nothing matched that search.",
    openMenu: "Open menu", menu: "Menu", closeMenu: "Close menu", language: "Language",
    backToTop: "Back to top", toggleDarkMode: "Toggle dark mode",
    toggleToc: "Toggle table of contents", close: "Close", map: "Map",
    carousel: "carousel", slide: "slide", prevSlide: "Previous slide", nextSlide: "Next slide",
    slideOf: (i, n) => `${i} of ${n}`, offerEnded: "This offer has ended",
    leaveAComment: "Leave a Comment", commentForms: { one: "Comment", other: "Comments" },
    yourName: "Name", yourEmail: "Email (not published)", yourWebsite: "Website (optional)",
    yourComment: "Your comment", postComment: "Post Comment", posting: "Posting…",
    commentPending: "Thanks — your comment has been sent and will appear once it is approved.",
    commentPosted: "Thanks — your comment has been posted.",
    postsBy: (n) => `Posts by ${n}`, siteTeam: "Written by the site team.",
    playVideo: "Play video", playVideoTitled: (t) => `Play video: ${t}`,
    noDateSet: "No date set",
    closedLabel: "Closed", fieldRequired: "{field} is required", invalidEmail: "Enter a valid email address",
    sendMessage: "Send message",
    reply: "Reply", cancelReply: "Cancel",
  },
  ar: {
    search: "بحث", searchPlaceholder: "ابحث…", openSearch: "فتح البحث",
    searchResultsFor: (q) => `نتائج البحث عن «${q}»`,
    closeSearch: "إغلاق البحث", noResults: "لا توجد نتائج مطابقة لبحثك.",
    openMenu: "فتح القائمة", menu: "القائمة", closeMenu: "إغلاق القائمة", language: "اللغة",
    backToTop: "العودة إلى الأعلى", toggleDarkMode: "تبديل الوضع الداكن",
    toggleToc: "تبديل جدول المحتويات", close: "إغلاق", map: "خريطة",
    carousel: "شريط عرض", slide: "شريحة", prevSlide: "الشريحة السابقة", nextSlide: "الشريحة التالية",
    slideOf: (i, n) => `${i} من ${n}`, offerEnded: "انتهى هذا العرض",
    leaveAComment: "اترك تعليقًا", commentForms: { zero: "تعليقات", one: "تعليق", two: "تعليقان", few: "تعليقات", many: "تعليقًا", other: "تعليق" },
    yourName: "الاسم", yourEmail: "البريد الإلكتروني (لن يُنشر)", yourWebsite: "الموقع الإلكتروني (اختياري)",
    yourComment: "تعليقك", postComment: "نشر التعليق", posting: "جارٍ النشر…",
    commentPending: "شكرًا لك — تم إرسال تعليقك وسيظهر بعد الموافقة عليه.",
    commentPosted: "شكرًا لك — تم نشر تعليقك.",
    postsBy: (n) => `مقالات ${n}`, siteTeam: "بقلم فريق الموقع.",
    playVideo: "تشغيل الفيديو", playVideoTitled: (t) => `تشغيل الفيديو: ${t}`,
    noDateSet: "لم يُحدَّد تاريخ",
    closedLabel: "مغلق", fieldRequired: "{field} مطلوب", invalidEmail: "أدخل بريدًا إلكترونيًا صالحًا",
    sendMessage: "إرسال الرسالة",
    reply: "رد", cancelReply: "إلغاء",
  },
  fr: {
    search: "Rechercher", searchPlaceholder: "Rechercher…", openSearch: "Ouvrir la recherche",
    searchResultsFor: (q) => `Résultats de recherche pour « ${q} »`,
    closeSearch: "Fermer la recherche", noResults: "Aucun résultat pour cette recherche.",
    openMenu: "Ouvrir le menu", menu: "Menu", closeMenu: "Fermer le menu", language: "Langue",
    backToTop: "Retour en haut", toggleDarkMode: "Basculer le mode sombre",
    toggleToc: "Afficher/masquer le sommaire", close: "Fermer", map: "Carte",
    carousel: "carrousel", slide: "diapositive", prevSlide: "Diapositive précédente", nextSlide: "Diapositive suivante",
    slideOf: (i, n) => `${i} sur ${n}`, offerEnded: "Cette offre est terminée",
    leaveAComment: "Laisser un commentaire", commentForms: { one: "commentaire", other: "commentaires" },
    yourName: "Nom", yourEmail: "E-mail (non publié)", yourWebsite: "Site web (facultatif)",
    yourComment: "Votre commentaire", postComment: "Publier le commentaire", posting: "Publication…",
    commentPending: "Merci — votre commentaire a été envoyé et paraîtra après validation.",
    commentPosted: "Merci — votre commentaire a été publié.",
    postsBy: (n) => `Articles de ${n}`, siteTeam: "Écrit par l’équipe du site.",
    playVideo: "Lire la vidéo", playVideoTitled: (t) => `Lire la vidéo : ${t}`,
    noDateSet: "Aucune date définie",
    closedLabel: "Fermé", fieldRequired: "{field} est obligatoire", invalidEmail: "Saisissez une adresse e-mail valide",
    sendMessage: "Envoyer le message",
    reply: "Répondre", cancelReply: "Annuler",
  },
  es: {
    search: "Buscar", searchPlaceholder: "Buscar…", openSearch: "Abrir búsqueda",
    searchResultsFor: (q) => `Resultados de búsqueda para «${q}»`,
    closeSearch: "Cerrar búsqueda", noResults: "No hay resultados para esa búsqueda.",
    openMenu: "Abrir menú", menu: "Menú", closeMenu: "Cerrar menú", language: "Idioma",
    backToTop: "Volver arriba", toggleDarkMode: "Alternar modo oscuro",
    toggleToc: "Mostrar u ocultar el índice", close: "Cerrar", map: "Mapa",
    carousel: "carrusel", slide: "diapositiva", prevSlide: "Diapositiva anterior", nextSlide: "Diapositiva siguiente",
    slideOf: (i, n) => `${i} de ${n}`, offerEnded: "Esta oferta ha terminado",
    leaveAComment: "Deja un comentario", commentForms: { one: "comentario", other: "comentarios" },
    yourName: "Nombre", yourEmail: "Correo electrónico (no se publica)", yourWebsite: "Sitio web (opcional)",
    yourComment: "Tu comentario", postComment: "Publicar comentario", posting: "Publicando…",
    commentPending: "Gracias — tu comentario se ha enviado y aparecerá cuando se apruebe.",
    commentPosted: "Gracias — tu comentario se ha publicado.",
    postsBy: (n) => `Entradas de ${n}`, siteTeam: "Escrito por el equipo del sitio.",
    playVideo: "Reproducir el vídeo", playVideoTitled: (t) => `Reproducir el vídeo: ${t}`,
    noDateSet: "Sin fecha definida",
    closedLabel: "Cerrado", fieldRequired: "{field} es obligatorio", invalidEmail: "Introduce una dirección de correo válida",
    sendMessage: "Enviar mensaje",
    reply: "Responder", cancelReply: "Cancelar",
  },
  pt: {
    search: "Pesquisar", searchPlaceholder: "Pesquisar…", openSearch: "Abrir pesquisa",
    searchResultsFor: (q) => `Resultados da pesquisa por “${q}”`,
    closeSearch: "Fechar pesquisa", noResults: "Nada corresponde a essa pesquisa.",
    openMenu: "Abrir menu", menu: "Menu", closeMenu: "Fechar menu", language: "Idioma",
    backToTop: "Voltar ao topo", toggleDarkMode: "Alternar modo escuro",
    toggleToc: "Mostrar ou ocultar o índice", close: "Fechar", map: "Mapa",
    carousel: "carrossel", slide: "slide", prevSlide: "Slide anterior", nextSlide: "Próximo slide",
    slideOf: (i, n) => `${i} de ${n}`, offerEnded: "Esta oferta terminou",
    leaveAComment: "Deixe um comentário", commentForms: { one: "comentário", other: "comentários" },
    yourName: "Nome", yourEmail: "E-mail (não publicado)", yourWebsite: "Site (opcional)",
    yourComment: "O seu comentário", postComment: "Publicar comentário", posting: "A publicar…",
    commentPending: "Obrigado — o seu comentário foi enviado e aparecerá depois de aprovado.",
    commentPosted: "Obrigado — o seu comentário foi publicado.",
    postsBy: (n) => `Artigos de ${n}`, siteTeam: "Escrito pela equipa do site.",
    playVideo: "Reproduzir o vídeo", playVideoTitled: (t) => `Reproduzir o vídeo: ${t}`,
    noDateSet: "Sem data definida",
    closedLabel: "Fechado", fieldRequired: "{field} é obrigatório", invalidEmail: "Introduza um endereço de e-mail válido",
    sendMessage: "Enviar mensagem",
    reply: "Responder", cancelReply: "Cancelar",
  },
  de: {
    search: "Suchen", searchPlaceholder: "Suchen…", openSearch: "Suche öffnen",
    searchResultsFor: (q) => `Suchergebnisse für „${q}“`,
    closeSearch: "Suche schließen", noResults: "Keine Treffer für diese Suche.",
    openMenu: "Menü öffnen", menu: "Menü", closeMenu: "Menü schließen", language: "Sprache",
    backToTop: "Nach oben", toggleDarkMode: "Dunkelmodus umschalten",
    toggleToc: "Inhaltsverzeichnis ein-/ausblenden", close: "Schließen", map: "Karte",
    carousel: "Karussell", slide: "Folie", prevSlide: "Vorherige Folie", nextSlide: "Nächste Folie",
    slideOf: (i, n) => `${i} von ${n}`, offerEnded: "Dieses Angebot ist abgelaufen",
    leaveAComment: "Kommentar schreiben", commentForms: { one: "Kommentar", other: "Kommentare" },
    yourName: "Name", yourEmail: "E-Mail (wird nicht veröffentlicht)", yourWebsite: "Website (optional)",
    yourComment: "Ihr Kommentar", postComment: "Kommentar absenden", posting: "Wird gesendet…",
    commentPending: "Danke — Ihr Kommentar wurde gesendet und erscheint nach der Freigabe.",
    commentPosted: "Danke — Ihr Kommentar wurde veröffentlicht.",
    postsBy: (n) => `Beiträge von ${n}`, siteTeam: "Vom Team der Website verfasst.",
    playVideo: "Video abspielen", playVideoTitled: (t) => `Video abspielen: ${t}`,
    noDateSet: "Kein Datum festgelegt",
    closedLabel: "Geschlossen", fieldRequired: "{field} ist erforderlich", invalidEmail: "Geben Sie eine gültige E-Mail-Adresse ein",
    sendMessage: "Nachricht senden",
    reply: "Antworten", cancelReply: "Abbrechen",
  },
  it: {
    search: "Cerca", searchPlaceholder: "Cerca…", openSearch: "Apri la ricerca",
    searchResultsFor: (q) => `Risultati della ricerca per «${q}»`,
    closeSearch: "Chiudi la ricerca", noResults: "Nessun risultato per questa ricerca.",
    openMenu: "Apri il menu", menu: "Menu", closeMenu: "Chiudi il menu", language: "Lingua",
    backToTop: "Torna su", toggleDarkMode: "Attiva/disattiva la modalità scura",
    toggleToc: "Mostra o nascondi l’indice", close: "Chiudi", map: "Mappa",
    carousel: "carosello", slide: "diapositiva", prevSlide: "Diapositiva precedente", nextSlide: "Diapositiva successiva",
    slideOf: (i, n) => `${i} di ${n}`, offerEnded: "Questa offerta è terminata",
    leaveAComment: "Lascia un commento", commentForms: { one: "commento", other: "commenti" },
    yourName: "Nome", yourEmail: "Email (non pubblicata)", yourWebsite: "Sito web (facoltativo)",
    yourComment: "Il tuo commento", postComment: "Pubblica il commento", posting: "Invio…",
    commentPending: "Grazie — il tuo commento è stato inviato e apparirà dopo l’approvazione.",
    commentPosted: "Grazie — il tuo commento è stato pubblicato.",
    postsBy: (n) => `Articoli di ${n}`, siteTeam: "Scritto dal team del sito.",
    playVideo: "Riproduci il video", playVideoTitled: (t) => `Riproduci il video: ${t}`,
    noDateSet: "Nessuna data impostata",
    closedLabel: "Chiuso", fieldRequired: "{field} è obbligatorio", invalidEmail: "Inserisci un indirizzo email valido",
    sendMessage: "Invia messaggio",
    reply: "Rispondi", cancelReply: "Annulla",
  },
  tr: {
    search: "Ara", searchPlaceholder: "Ara…", openSearch: "Aramayı aç",
    searchResultsFor: (q) => `“${q}” için arama sonuçları`,
    closeSearch: "Aramayı kapat", noResults: "Bu aramayla eşleşen bir şey yok.",
    openMenu: "Menüyü aç", menu: "Menü", closeMenu: "Menüyü kapat", language: "Dil",
    backToTop: "Yukarı dön", toggleDarkMode: "Koyu modu aç/kapat",
    toggleToc: "İçindekiler tablosunu aç/kapat", close: "Kapat", map: "Harita",
    carousel: "galeri", slide: "slayt", prevSlide: "Önceki slayt", nextSlide: "Sonraki slayt",
    slideOf: (i, n) => `${n} slayttan ${i}.`, offerEnded: "Bu teklif sona erdi",
    leaveAComment: "Yorum bırakın", commentForms: { other: "yorum" },
    yourName: "Ad", yourEmail: "E-posta (yayımlanmaz)", yourWebsite: "Web sitesi (isteğe bağlı)",
    yourComment: "Yorumunuz", postComment: "Yorumu gönder", posting: "Gönderiliyor…",
    commentPending: "Teşekkürler — yorumunuz gönderildi, onaylandığında görünecek.",
    commentPosted: "Teşekkürler — yorumunuz yayımlandı.",
    postsBy: (n) => `${n} tarafından yazılan yazılar`, siteTeam: "Site ekibi tarafından yazıldı.",
    playVideo: "Videoyu oynat", playVideoTitled: (t) => `Videoyu oynat: ${t}`,
    noDateSet: "Tarih belirlenmedi",
    closedLabel: "Kapalı", fieldRequired: "{field} zorunludur", invalidEmail: "Geçerli bir e-posta adresi girin",
    sendMessage: "Mesaj gönder",
    reply: "Yanıtla", cancelReply: "İptal",
  },
  ru: {
    search: "Поиск", searchPlaceholder: "Поиск…", openSearch: "Открыть поиск",
    searchResultsFor: (q) => `Результаты поиска по запросу «${q}»`,
    closeSearch: "Закрыть поиск", noResults: "По этому запросу ничего не найдено.",
    openMenu: "Открыть меню", menu: "Меню", closeMenu: "Закрыть меню", language: "Язык",
    backToTop: "Наверх", toggleDarkMode: "Переключить тёмную тему",
    toggleToc: "Показать или скрыть оглавление", close: "Закрыть", map: "Карта",
    carousel: "карусель", slide: "слайд", prevSlide: "Предыдущий слайд", nextSlide: "Следующий слайд",
    slideOf: (i, n) => `${i} из ${n}`, offerEnded: "Срок этого предложения истёк",
    leaveAComment: "Оставить комментарий", commentForms: { one: "комментарий", few: "комментария", many: "комментариев", other: "комментария" },
    yourName: "Имя", yourEmail: "Эл. почта (не публикуется)", yourWebsite: "Сайт (необязательно)",
    yourComment: "Ваш комментарий", postComment: "Отправить комментарий", posting: "Отправка…",
    commentPending: "Спасибо — ваш комментарий отправлен и появится после проверки.",
    commentPosted: "Спасибо — ваш комментарий опубликован.",
    postsBy: (n) => `Записи автора ${n}`, siteTeam: "Написано командой сайта.",
    playVideo: "Воспроизвести видео", playVideoTitled: (t) => `Воспроизвести видео: ${t}`,
    noDateSet: "Дата не задана",
    closedLabel: "Закрыто", fieldRequired: "Поле «{field}» обязательно", invalidEmail: "Введите действительный адрес электронной почты",
    sendMessage: "Отправить сообщение",
    reply: "Ответить", cancelReply: "Отмена",
  },
  ur: {
    search: "تلاش", searchPlaceholder: "تلاش کریں…", openSearch: "تلاش کھولیں",
    searchResultsFor: (q) => `“${q}” کے لیے تلاش کے نتائج`,
    closeSearch: "تلاش بند کریں", noResults: "اس تلاش سے کچھ نہیں ملا۔",
    openMenu: "مینو کھولیں", menu: "مینو", closeMenu: "مینو بند کریں", language: "زبان",
    backToTop: "اوپر واپس جائیں", toggleDarkMode: "ڈارک موڈ تبدیل کریں",
    toggleToc: "فہرستِ مضامین دکھائیں یا چھپائیں", close: "بند کریں", map: "نقشہ",
    carousel: "سلائیڈ شو", slide: "سلائیڈ", prevSlide: "پچھلی سلائیڈ", nextSlide: "اگلی سلائیڈ",
    slideOf: (i, n) => `${n} میں سے ${i}`, offerEnded: "یہ پیشکش ختم ہو گئی ہے",
    leaveAComment: "تبصرہ کریں", commentForms: { one: "تبصرہ", other: "تبصرے" },
    yourName: "نام", yourEmail: "ای میل (شائع نہیں ہوگا)", yourWebsite: "ویب سائٹ (اختیاری)",
    yourComment: "آپ کا تبصرہ", postComment: "تبصرہ شائع کریں", posting: "شائع ہو رہا ہے…",
    commentPending: "شکریہ — آپ کا تبصرہ بھیج دیا گیا ہے اور منظوری کے بعد ظاہر ہوگا۔",
    commentPosted: "شکریہ — آپ کا تبصرہ شائع ہو گیا ہے۔",
    postsBy: (n) => `${n} کے مضامین`, siteTeam: "سائٹ ٹیم کی تحریر۔",
    playVideo: "ویڈیو چلائیں", playVideoTitled: (t) => `ویڈیو چلائیں: ${t}`,
    noDateSet: "کوئی تاریخ مقرر نہیں",
    closedLabel: "بند", fieldRequired: "{field} درکار ہے", invalidEmail: "درست ای میل ایڈریس درج کریں",
    sendMessage: "پیغام بھیجیں",
    reply: "جواب دیں", cancelReply: "منسوخ کریں",
  },
  fa: {
    search: "جستجو", searchPlaceholder: "جستجو…", openSearch: "باز کردن جستجو",
    searchResultsFor: (q) => `نتایج جستجو برای «${q}»`,
    closeSearch: "بستن جستجو", noResults: "چیزی با این جستجو پیدا نشد.",
    openMenu: "باز کردن منو", menu: "منو", closeMenu: "بستن منو", language: "زبان",
    backToTop: "بازگشت به بالا", toggleDarkMode: "تغییر حالت تاریک",
    toggleToc: "نمایش یا پنهان‌کردن فهرست مطالب", close: "بستن", map: "نقشه",
    carousel: "چرخ‌فلک", slide: "اسلاید", prevSlide: "اسلاید قبلی", nextSlide: "اسلاید بعدی",
    slideOf: (i, n) => `${i} از ${n}`, offerEnded: "این پیشنهاد به پایان رسیده است",
    leaveAComment: "دیدگاه بگذارید", commentForms: { other: "دیدگاه" },
    yourName: "نام", yourEmail: "ایمیل (منتشر نمی‌شود)", yourWebsite: "وب‌سایت (اختیاری)",
    yourComment: "دیدگاه شما", postComment: "ثبت دیدگاه", posting: "در حال ثبت…",
    commentPending: "سپاسگزاریم — دیدگاه شما ارسال شد و پس از تأیید نمایش داده می‌شود.",
    commentPosted: "سپاسگزاریم — دیدگاه شما ثبت شد.",
    postsBy: (n) => `نوشته‌های ${n}`, siteTeam: "نوشتهٔ تیم سایت.",
    playVideo: "پخش ویدئو", playVideoTitled: (t) => `پخش ویدئو: ${t}`,
    noDateSet: "تاریخی تعیین نشده",
    closedLabel: "تعطیل", fieldRequired: "{field} الزامی است", invalidEmail: "یک نشانی ایمیل معتبر وارد کنید",
    sendMessage: "ارسال پیام",
    reply: "پاسخ", cancelReply: "لغو",
  },
  hi: {
    search: "खोजें", searchPlaceholder: "खोजें…", openSearch: "खोज खोलें",
    searchResultsFor: (q) => `“${q}” के लिए खोज परिणाम`,
    closeSearch: "खोज बंद करें", noResults: "इस खोज से कुछ नहीं मिला।",
    openMenu: "मेन्यू खोलें", menu: "मेन्यू", closeMenu: "मेन्यू बंद करें", language: "भाषा",
    backToTop: "ऊपर जाएँ", toggleDarkMode: "डार्क मोड बदलें",
    toggleToc: "विषय-सूची दिखाएँ या छिपाएँ", close: "बंद करें", map: "मानचित्र",
    carousel: "कैरसेल", slide: "स्लाइड", prevSlide: "पिछली स्लाइड", nextSlide: "अगली स्लाइड",
    slideOf: (i, n) => `${n} में से ${i}`, offerEnded: "यह ऑफ़र समाप्त हो गया है",
    leaveAComment: "टिप्पणी करें", commentForms: { other: "टिप्पणियाँ" },
    yourName: "नाम", yourEmail: "ईमेल (प्रकाशित नहीं होगा)", yourWebsite: "वेबसाइट (वैकल्पिक)",
    yourComment: "आपकी टिप्पणी", postComment: "टिप्पणी भेजें", posting: "भेजा जा रहा है…",
    commentPending: "धन्यवाद — आपकी टिप्पणी भेज दी गई है और स्वीकृति के बाद दिखाई देगी।",
    commentPosted: "धन्यवाद — आपकी टिप्पणी प्रकाशित हो गई है।",
    postsBy: (n) => `${n} के लेख`, siteTeam: "साइट टीम द्वारा लिखित।",
    playVideo: "वीडियो चलाएँ", playVideoTitled: (t) => `वीडियो चलाएँ: ${t}`,
    noDateSet: "कोई तिथि तय नहीं",
    closedLabel: "बंद", fieldRequired: "{field} आवश्यक है", invalidEmail: "मान्य ईमेल पता दर्ज करें",
    sendMessage: "संदेश भेजें",
    reply: "उत्तर दें", cancelReply: "रद्द करें",
  },
  id: {
    search: "Cari", searchPlaceholder: "Cari…", openSearch: "Buka pencarian",
    searchResultsFor: (q) => `Hasil pencarian untuk “${q}”`,
    closeSearch: "Tutup pencarian", noResults: "Tidak ada yang cocok dengan pencarian itu.",
    openMenu: "Buka menu", menu: "Menu", closeMenu: "Tutup menu", language: "Bahasa",
    backToTop: "Kembali ke atas", toggleDarkMode: "Alihkan mode gelap",
    toggleToc: "Tampilkan atau sembunyikan daftar isi", close: "Tutup", map: "Peta",
    carousel: "korsel", slide: "salindia", prevSlide: "Salindia sebelumnya", nextSlide: "Salindia berikutnya",
    slideOf: (i, n) => `${i} dari ${n}`, offerEnded: "Penawaran ini telah berakhir",
    leaveAComment: "Tinggalkan komentar", commentForms: { other: "komentar" },
    yourName: "Nama", yourEmail: "Email (tidak dipublikasikan)", yourWebsite: "Situs web (opsional)",
    yourComment: "Komentar Anda", postComment: "Kirim komentar", posting: "Mengirim…",
    commentPending: "Terima kasih — komentar Anda telah dikirim dan akan tampil setelah disetujui.",
    commentPosted: "Terima kasih — komentar Anda telah dipublikasikan.",
    postsBy: (n) => `Artikel oleh ${n}`, siteTeam: "Ditulis oleh tim situs.",
    playVideo: "Putar video", playVideoTitled: (t) => `Putar video: ${t}`,
    noDateSet: "Tanggal belum diatur",
    closedLabel: "Tutup", fieldRequired: "{field} wajib diisi", invalidEmail: "Masukkan alamat email yang valid",
    sendMessage: "Kirim pesan",
    reply: "Balas", cancelReply: "Batal",
  },
  nl: {
    search: "Zoeken", searchPlaceholder: "Zoeken…", openSearch: "Zoeken openen",
    closeSearch: "Zoeken sluiten",
    searchResultsFor: (q) => `Zoekresultaten voor “${q}”`,
    noResults: "Niets gevonden voor die zoekopdracht.",
    openMenu: "Menu openen", menu: "Menu", closeMenu: "Menu sluiten", language: "Taal",
    backToTop: "Terug naar boven", toggleDarkMode: "Donkere modus wisselen",
    toggleToc: "Inhoudsopgave tonen of verbergen", close: "Sluiten", map: "Kaart",
    carousel: "carrousel", slide: "dia", prevSlide: "Vorige dia", nextSlide: "Volgende dia",
    slideOf: (i, n) => `${i} van ${n}`, offerEnded: "Deze aanbieding is afgelopen",
    leaveAComment: "Laat een reactie achter", commentForms: { one: "reactie", other: "reacties" },
    yourName: "Naam", yourEmail: "E-mail (wordt niet gepubliceerd)", yourWebsite: "Website (optioneel)",
    yourComment: "Uw reactie", postComment: "Reactie plaatsen", posting: "Bezig met plaatsen…",
    commentPending: "Bedankt — uw reactie is verzonden en verschijnt zodra deze is goedgekeurd.",
    commentPosted: "Bedankt — uw reactie is geplaatst.",
    postsBy: (n) => `Berichten van ${n}`, siteTeam: "Geschreven door het siteteam.",
    playVideo: "Video afspelen", playVideoTitled: (t) => `Video afspelen: ${t}`,
    noDateSet: "Geen datum ingesteld",
    closedLabel: "Gesloten", fieldRequired: "{field} is verplicht", invalidEmail: "Voer een geldig e-mailadres in",
    sendMessage: "Bericht versturen",
    reply: "Reageren", cancelReply: "Annuleren",
  },
  pl: {
    search: "Szukaj", searchPlaceholder: "Szukaj…", openSearch: "Otwórz wyszukiwanie",
    closeSearch: "Zamknij wyszukiwanie",
    searchResultsFor: (q) => `Wyniki wyszukiwania dla „${q}”`,
    noResults: "Brak wyników dla tego zapytania.",
    openMenu: "Otwórz menu", menu: "Menu", closeMenu: "Zamknij menu", language: "Język",
    backToTop: "Powrót na górę", toggleDarkMode: "Przełącz tryb ciemny",
    toggleToc: "Pokaż lub ukryj spis treści", close: "Zamknij", map: "Mapa",
    carousel: "karuzela", slide: "slajd", prevSlide: "Poprzedni slajd", nextSlide: "Następny slajd",
    slideOf: (i, n) => `${i} z ${n}`, offerEnded: "Ta oferta zakończyła się",
    leaveAComment: "Dodaj komentarz", commentForms: { one: "komentarz", few: "komentarze", many: "komentarzy", other: "komentarza" },
    yourName: "Imię", yourEmail: "E-mail (nie zostanie opublikowany)", yourWebsite: "Strona internetowa (opcjonalnie)",
    yourComment: "Twój komentarz", postComment: "Opublikuj komentarz", posting: "Wysyłanie…",
    commentPending: "Dziękujemy — komentarz został wysłany i pojawi się po zatwierdzeniu.",
    commentPosted: "Dziękujemy — komentarz został opublikowany.",
    postsBy: (n) => `Artykuły autora ${n}`, siteTeam: "Napisane przez zespół serwisu.",
    playVideo: "Odtwórz wideo", playVideoTitled: (t) => `Odtwórz wideo: ${t}`,
    noDateSet: "Nie ustawiono daty",
    closedLabel: "Zamknięte", fieldRequired: "Pole {field} jest wymagane", invalidEmail: "Podaj prawidłowy adres e-mail",
    sendMessage: "Wyślij wiadomość",
    reply: "Odpowiedz", cancelReply: "Anuluj",
  },
  uk: {
    search: "Пошук", searchPlaceholder: "Пошук…", openSearch: "Відкрити пошук",
    closeSearch: "Закрити пошук",
    searchResultsFor: (q) => `Результати пошуку за запитом «${q}»`,
    noResults: "За цим запитом нічого не знайдено.",
    openMenu: "Відкрити меню", menu: "Меню", closeMenu: "Закрити меню", language: "Мова",
    backToTop: "Нагору", toggleDarkMode: "Перемкнути темну тему",
    toggleToc: "Показати або приховати зміст", close: "Закрити", map: "Карта",
    carousel: "карусель", slide: "слайд", prevSlide: "Попередній слайд", nextSlide: "Наступний слайд",
    slideOf: (i, n) => `${i} з ${n}`, offerEnded: "Термін цієї пропозиції завершився",
    leaveAComment: "Залишити коментар", commentForms: { one: "коментар", few: "коментарі", many: "коментарів", other: "коментаря" },
    yourName: "Ім'я", yourEmail: "Ел. пошта (не публікується)", yourWebsite: "Сайт (необов'язково)",
    yourComment: "Ваш коментар", postComment: "Надіслати коментар", posting: "Надсилання…",
    commentPending: "Дякуємо — ваш коментар надіслано, він з'явиться після схвалення.",
    commentPosted: "Дякуємо — ваш коментар опубліковано.",
    postsBy: (n) => `Записи автора ${n}`, siteTeam: "Написано командою сайту.",
    playVideo: "Відтворити відео", playVideoTitled: (t) => `Відтворити відео: ${t}`,
    noDateSet: "Дату не встановлено",
    closedLabel: "Зачинено", fieldRequired: "Поле «{field}» обов’язкове", invalidEmail: "Введіть дійсну адресу електронної пошти",
    sendMessage: "Надіслати повідомлення",
    reply: "Відповісти", cancelReply: "Скасувати",
  },
  cs: {
    search: "Hledat", searchPlaceholder: "Hledat…", openSearch: "Otevřít vyhledávání",
    closeSearch: "Zavřít vyhledávání",
    searchResultsFor: (q) => `Výsledky hledání pro „${q}“`,
    noResults: "Tomuto hledání nic neodpovídá.",
    openMenu: "Otevřít menu", menu: "Menu", closeMenu: "Zavřít menu", language: "Jazyk",
    backToTop: "Zpět nahoru", toggleDarkMode: "Přepnout tmavý režim",
    toggleToc: "Zobrazit nebo skrýt obsah", close: "Zavřít", map: "Mapa",
    carousel: "karusel", slide: "snímek", prevSlide: "Předchozí snímek", nextSlide: "Další snímek",
    slideOf: (i, n) => `${i} z ${n}`, offerEnded: "Tato nabídka skončila",
    leaveAComment: "Napsat komentář", commentForms: { one: "komentář", few: "komentáře", many: "komentáře", other: "komentářů" },
    yourName: "Jméno", yourEmail: "E-mail (nebude zveřejněn)", yourWebsite: "Web (nepovinné)",
    yourComment: "Váš komentář", postComment: "Odeslat komentář", posting: "Odesílání…",
    commentPending: "Děkujeme — váš komentář byl odeslán a objeví se po schválení.",
    commentPosted: "Děkujeme — váš komentář byl zveřejněn.",
    postsBy: (n) => `Články autora ${n}`, siteTeam: "Napsal tým webu.",
    playVideo: "Přehrát video", playVideoTitled: (t) => `Přehrát video: ${t}`,
    noDateSet: "Datum nenastaveno",
    closedLabel: "Zavřeno", fieldRequired: "{field} je povinné", invalidEmail: "Zadejte platnou e-mailovou adresu",
    sendMessage: "Odeslat zprávu",
    reply: "Odpovědět", cancelReply: "Zrušit",
  },
  el: {
    search: "Αναζήτηση", searchPlaceholder: "Αναζήτηση…", openSearch: "Άνοιγμα αναζήτησης",
    closeSearch: "Κλείσιμο αναζήτησης",
    searchResultsFor: (q) => `Αποτελέσματα αναζήτησης για «${q}»`,
    noResults: "Δεν βρέθηκε τίποτα για αυτή την αναζήτηση.",
    openMenu: "Άνοιγμα μενού", menu: "Μενού", closeMenu: "Κλείσιμο μενού", language: "Γλώσσα",
    backToTop: "Επιστροφή πάνω", toggleDarkMode: "Εναλλαγή σκοτεινής λειτουργίας",
    toggleToc: "Εμφάνιση ή απόκρυψη περιεχομένων", close: "Κλείσιμο", map: "Χάρτης",
    carousel: "καρουζέλ", slide: "διαφάνεια", prevSlide: "Προηγούμενη διαφάνεια", nextSlide: "Επόμενη διαφάνεια",
    slideOf: (i, n) => `${i} από ${n}`, offerEnded: "Αυτή η προσφορά έχει λήξει",
    leaveAComment: "Αφήστε ένα σχόλιο", commentForms: { one: "σχόλιο", other: "σχόλια" },
    yourName: "Όνομα", yourEmail: "Email (δεν δημοσιεύεται)", yourWebsite: "Ιστότοπος (προαιρετικό)",
    yourComment: "Το σχόλιό σας", postComment: "Υποβολή σχολίου", posting: "Αποστολή…",
    commentPending: "Ευχαριστούμε — το σχόλιό σας στάλθηκε και θα εμφανιστεί μετά την έγκριση.",
    commentPosted: "Ευχαριστούμε — το σχόλιό σας δημοσιεύτηκε.",
    postsBy: (n) => `Άρθρα του/της ${n}`, siteTeam: "Γράφτηκε από την ομάδα του ιστότοπου.",
    playVideo: "Αναπαραγωγή βίντεο", playVideoTitled: (t) => `Αναπαραγωγή βίντεο: ${t}`,
    noDateSet: "Δεν ορίστηκε ημερομηνία",
    closedLabel: "Κλειστά", fieldRequired: "Το πεδίο {field} είναι υποχρεωτικό", invalidEmail: "Εισαγάγετε έγκυρη διεύθυνση email",
    sendMessage: "Αποστολή μηνύματος",
    reply: "Απάντηση", cancelReply: "Ακύρωση",
  },
  ro: {
    search: "Caută", searchPlaceholder: "Caută…", openSearch: "Deschide căutarea",
    closeSearch: "Închide căutarea",
    searchResultsFor: (q) => `Rezultate pentru „${q}”`,
    noResults: "Nimic nu corespunde acestei căutări.",
    openMenu: "Deschide meniul", menu: "Meniu", closeMenu: "Închide meniul", language: "Limbă",
    backToTop: "Înapoi sus", toggleDarkMode: "Comută modul întunecat",
    toggleToc: "Arată sau ascunde cuprinsul", close: "Închide", map: "Hartă",
    carousel: "carusel", slide: "diapozitiv", prevSlide: "Diapozitivul anterior", nextSlide: "Diapozitivul următor",
    slideOf: (i, n) => `${i} din ${n}`, offerEnded: "Această ofertă s-a încheiat",
    leaveAComment: "Lasă un comentariu", commentForms: { one: "comentariu", few: "comentarii", other: "de comentarii" },
    yourName: "Nume", yourEmail: "E-mail (nu se publică)", yourWebsite: "Site web (opțional)",
    yourComment: "Comentariul tău", postComment: "Trimite comentariul", posting: "Se trimite…",
    commentPending: "Mulțumim — comentariul a fost trimis și va apărea după aprobare.",
    commentPosted: "Mulțumim — comentariul a fost publicat.",
    postsBy: (n) => `Articole de ${n}`, siteTeam: "Scris de echipa site-ului.",
    playVideo: "Redă videoclipul", playVideoTitled: (t) => `Redă videoclipul: ${t}`,
    noDateSet: "Nicio dată setată",
    closedLabel: "Închis", fieldRequired: "{field} este obligatoriu", invalidEmail: "Introduceți o adresă de e-mail validă",
    sendMessage: "Trimite mesajul",
    reply: "Răspunde", cancelReply: "Anulează",
  },
  hu: {
    search: "Keresés", searchPlaceholder: "Keresés…", openSearch: "Keresés megnyitása",
    closeSearch: "Keresés bezárása",
    searchResultsFor: (q) => `Találatok erre: „${q}”`,
    noResults: "Nincs találat erre a keresésre.",
    openMenu: "Menü megnyitása", menu: "Menü", closeMenu: "Menü bezárása", language: "Nyelv",
    backToTop: "Vissza a tetejére", toggleDarkMode: "Sötét mód váltása",
    toggleToc: "Tartalomjegyzék mutatása vagy elrejtése", close: "Bezárás", map: "Térkép",
    carousel: "körhinta", slide: "dia", prevSlide: "Előző dia", nextSlide: "Következő dia",
    slideOf: (i, n) => `${n} / ${i}`, offerEnded: "Ez az ajánlat lejárt",
    leaveAComment: "Szólj hozzá", commentForms: { other: "hozzászólás" },
    yourName: "Név", yourEmail: "E-mail (nem jelenik meg)", yourWebsite: "Weboldal (nem kötelező)",
    yourComment: "Hozzászólásod", postComment: "Hozzászólás küldése", posting: "Küldés…",
    commentPending: "Köszönjük — a hozzászólás elküldve, jóváhagyás után jelenik meg.",
    commentPosted: "Köszönjük — a hozzászólás közzétéve.",
    postsBy: (n) => `${n} bejegyzései`, siteTeam: "A weboldal csapata írta.",
    playVideo: "Videó lejátszása", playVideoTitled: (t) => `Videó lejátszása: ${t}`,
    noDateSet: "Nincs dátum beállítva",
    closedLabel: "Zárva", fieldRequired: "A(z) {field} megadása kötelező", invalidEmail: "Adjon meg egy érvényes e-mail-címet",
    sendMessage: "Üzenet küldése",
    reply: "Válasz", cancelReply: "Mégse",
  },
  sv: {
    search: "Sök", searchPlaceholder: "Sök…", openSearch: "Öppna sökningen",
    closeSearch: "Stäng sökningen",
    searchResultsFor: (q) => `Sökresultat för ”${q}”`,
    noResults: "Inget matchade den sökningen.",
    openMenu: "Öppna menyn", menu: "Meny", closeMenu: "Stäng menyn", language: "Språk",
    backToTop: "Tillbaka till toppen", toggleDarkMode: "Växla mörkt läge",
    toggleToc: "Visa eller dölj innehållsförteckningen", close: "Stäng", map: "Karta",
    carousel: "karusell", slide: "bild", prevSlide: "Föregående bild", nextSlide: "Nästa bild",
    slideOf: (i, n) => `${i} av ${n}`, offerEnded: "Det här erbjudandet har avslutats",
    leaveAComment: "Lämna en kommentar", commentForms: { one: "kommentar", other: "kommentarer" },
    yourName: "Namn", yourEmail: "E-post (publiceras inte)", yourWebsite: "Webbplats (valfritt)",
    yourComment: "Din kommentar", postComment: "Skicka kommentar", posting: "Skickar…",
    commentPending: "Tack — din kommentar har skickats och visas när den har godkänts.",
    commentPosted: "Tack — din kommentar har publicerats.",
    postsBy: (n) => `Inlägg av ${n}`, siteTeam: "Skriven av webbplatsens team.",
    playVideo: "Spela upp videon", playVideoTitled: (t) => `Spela upp videon: ${t}`,
    noDateSet: "Inget datum angivet",
    closedLabel: "Stängt", fieldRequired: "{field} är obligatoriskt", invalidEmail: "Ange en giltig e-postadress",
    sendMessage: "Skicka meddelande",
    reply: "Svara", cancelReply: "Avbryt",
  },
  da: {
    search: "Søg", searchPlaceholder: "Søg…", openSearch: "Åbn søgning",
    closeSearch: "Luk søgning",
    searchResultsFor: (q) => `Søgeresultater for ”${q}”`,
    noResults: "Intet matchede den søgning.",
    openMenu: "Åbn menu", menu: "Menu", closeMenu: "Luk menu", language: "Sprog",
    backToTop: "Tilbage til toppen", toggleDarkMode: "Skift mørk tilstand",
    toggleToc: "Vis eller skjul indholdsfortegnelsen", close: "Luk", map: "Kort",
    carousel: "karrusel", slide: "slide", prevSlide: "Forrige slide", nextSlide: "Næste slide",
    slideOf: (i, n) => `${i} af ${n}`, offerEnded: "Dette tilbud er udløbet",
    leaveAComment: "Skriv en kommentar", commentForms: { one: "kommentar", other: "kommentarer" },
    yourName: "Navn", yourEmail: "E-mail (offentliggøres ikke)", yourWebsite: "Websted (valgfrit)",
    yourComment: "Din kommentar", postComment: "Send kommentar", posting: "Sender…",
    commentPending: "Tak — din kommentar er sendt og vises, når den er godkendt.",
    commentPosted: "Tak — din kommentar er udgivet.",
    postsBy: (n) => `Indlæg af ${n}`, siteTeam: "Skrevet af webstedets team.",
    playVideo: "Afspil videoen", playVideoTitled: (t) => `Afspil videoen: ${t}`,
    noDateSet: "Ingen dato angivet",
    closedLabel: "Lukket", fieldRequired: "{field} er påkrævet", invalidEmail: "Indtast en gyldig e-mailadresse",
    sendMessage: "Send besked",
    reply: "Svar", cancelReply: "Annuller",
  },
  nb: {
    search: "Søk", searchPlaceholder: "Søk…", openSearch: "Åpne søk",
    closeSearch: "Lukk søk",
    searchResultsFor: (q) => `Søkeresultater for «${q}»`,
    noResults: "Ingenting samsvarte med det søket.",
    openMenu: "Åpne menyen", menu: "Meny", closeMenu: "Lukk menyen", language: "Språk",
    backToTop: "Tilbake til toppen", toggleDarkMode: "Veksle mørk modus",
    toggleToc: "Vis eller skjul innholdsfortegnelsen", close: "Lukk", map: "Kart",
    carousel: "karusell", slide: "lysbilde", prevSlide: "Forrige lysbilde", nextSlide: "Neste lysbilde",
    slideOf: (i, n) => `${i} av ${n}`, offerEnded: "Dette tilbudet er avsluttet",
    leaveAComment: "Legg igjen en kommentar", commentForms: { one: "kommentar", other: "kommentarer" },
    yourName: "Navn", yourEmail: "E-post (publiseres ikke)", yourWebsite: "Nettsted (valgfritt)",
    yourComment: "Kommentaren din", postComment: "Send kommentar", posting: "Sender…",
    commentPending: "Takk — kommentaren er sendt og vises når den er godkjent.",
    commentPosted: "Takk — kommentaren er publisert.",
    postsBy: (n) => `Innlegg av ${n}`, siteTeam: "Skrevet av nettstedets team.",
    playVideo: "Spill av videoen", playVideoTitled: (t) => `Spill av videoen: ${t}`,
    noDateSet: "Ingen dato angitt",
    closedLabel: "Stengt", fieldRequired: "{field} er påkrevd", invalidEmail: "Skriv inn en gyldig e-postadresse",
    sendMessage: "Send melding",
    reply: "Svar", cancelReply: "Avbryt",
  },
  fi: {
    search: "Haku", searchPlaceholder: "Haku…", openSearch: "Avaa haku",
    closeSearch: "Sulje haku",
    searchResultsFor: (q) => `Hakutulokset haulle ”${q}”`,
    noResults: "Haulla ei löytynyt mitään.",
    openMenu: "Avaa valikko", menu: "Valikko", closeMenu: "Sulje valikko", language: "Kieli",
    backToTop: "Takaisin ylhäälle", toggleDarkMode: "Vaihda tummaa tilaa",
    toggleToc: "Näytä tai piilota sisällysluettelo", close: "Sulje", map: "Kartta",
    carousel: "karuselli", slide: "dia", prevSlide: "Edellinen dia", nextSlide: "Seuraava dia",
    slideOf: (i, n) => `${i} / ${n}`, offerEnded: "Tämä tarjous on päättynyt",
    leaveAComment: "Jätä kommentti", commentForms: { one: "kommentti", other: "kommenttia" },
    yourName: "Nimi", yourEmail: "Sähköposti (ei julkaista)", yourWebsite: "Verkkosivusto (valinnainen)",
    yourComment: "Kommenttisi", postComment: "Lähetä kommentti", posting: "Lähetetään…",
    commentPending: "Kiitos — kommenttisi on lähetetty ja näkyy hyväksynnän jälkeen.",
    commentPosted: "Kiitos — kommenttisi on julkaistu.",
    postsBy: (n) => `Kirjoittajan ${n} artikkelit`, siteTeam: "Sivuston tiimin kirjoittama.",
    playVideo: "Toista video", playVideoTitled: (t) => `Toista video: ${t}`,
    noDateSet: "Päivämäärää ei asetettu",
    closedLabel: "Suljettu", fieldRequired: "{field} on pakollinen", invalidEmail: "Anna kelvollinen sähköpostiosoite",
    sendMessage: "Lähetä viesti",
    reply: "Vastaa", cancelReply: "Peruuta",
  },
  he: {
    search: "חיפוש", searchPlaceholder: "חיפוש…", openSearch: "פתח חיפוש",
    closeSearch: "סגור חיפוש",
    searchResultsFor: (q) => `תוצאות חיפוש עבור ”${q}”`,
    noResults: "לא נמצאו תוצאות לחיפוש זה.",
    openMenu: "פתח תפריט", menu: "תפריט", closeMenu: "סגור תפריט", language: "שפה",
    backToTop: "חזרה למעלה", toggleDarkMode: "החלף מצב כהה",
    toggleToc: "הצג או הסתר את תוכן העניינים", close: "סגור", map: "מפה",
    carousel: "קרוסלה", slide: "שקופית", prevSlide: "השקופית הקודמת", nextSlide: "השקופית הבאה",
    slideOf: (i, n) => `${i} מתוך ${n}`, offerEnded: "המבצע הזה הסתיים",
    leaveAComment: "השאר תגובה", commentForms: { one: "תגובה", two: "תגובות", other: "תגובות" },
    yourName: "שם", yourEmail: "אימייל (לא יפורסם)", yourWebsite: "אתר (אופציונלי)",
    yourComment: "התגובה שלך", postComment: "שלח תגובה", posting: "שולח…",
    commentPending: "תודה — התגובה נשלחה ותופיע לאחר אישור.",
    commentPosted: "תודה — התגובה פורסמה.",
    postsBy: (n) => `פוסטים מאת ${n}`, siteTeam: "נכתב על ידי צוות האתר.",
    playVideo: "הפעל וידאו", playVideoTitled: (t) => `הפעל וידאו: ${t}`,
    noDateSet: "לא נקבע תאריך",
    closedLabel: "סגור", fieldRequired: "יש למלא {field}", invalidEmail: "הזינו כתובת אימייל תקינה",
    sendMessage: "שליחת הודעה",
    reply: "השב", cancelReply: "ביטול",
  },
  ja: {
    search: "検索", searchPlaceholder: "検索…", openSearch: "検索を開く",
    closeSearch: "検索を閉じる",
    searchResultsFor: (q) => `「${q}」の検索結果`,
    noResults: "検索に一致するものはありませんでした。",
    openMenu: "メニューを開く", menu: "メニュー", closeMenu: "メニューを閉じる", language: "言語",
    backToTop: "トップに戻る", toggleDarkMode: "ダークモードを切り替え",
    toggleToc: "目次の表示を切り替え", close: "閉じる", map: "地図",
    carousel: "カルーセル", slide: "スライド", prevSlide: "前のスライド", nextSlide: "次のスライド",
    slideOf: (i, n) => `${n} 中 ${i}`, offerEnded: "このオファーは終了しました",
    leaveAComment: "コメントを残す", commentForms: { other: "件のコメント" },
    yourName: "お名前", yourEmail: "メールアドレス（公開されません）", yourWebsite: "ウェブサイト（任意）",
    yourComment: "コメント", postComment: "コメントを送信", posting: "送信中…",
    commentPending: "ありがとうございます — コメントを送信しました。承認後に表示されます。",
    commentPosted: "ありがとうございます — コメントを公開しました。",
    postsBy: (n) => `${n} の記事`, siteTeam: "サイトチーム執筆。",
    playVideo: "動画を再生", playVideoTitled: (t) => `動画を再生: ${t}`,
    noDateSet: "日付が未設定です",
    closedLabel: "定休日", fieldRequired: "{field} は必須です", invalidEmail: "有効なメールアドレスを入力してください",
    sendMessage: "メッセージを送信",
    reply: "返信", cancelReply: "キャンセル",
  },
  ko: {
    search: "검색", searchPlaceholder: "검색…", openSearch: "검색 열기",
    closeSearch: "검색 닫기",
    searchResultsFor: (q) => `“${q}” 검색 결과`,
    noResults: "검색 결과가 없습니다.",
    openMenu: "메뉴 열기", menu: "메뉴", closeMenu: "메뉴 닫기", language: "언어",
    backToTop: "맨 위로", toggleDarkMode: "다크 모드 전환",
    toggleToc: "목차 표시/숨김", close: "닫기", map: "지도",
    carousel: "캐러셀", slide: "슬라이드", prevSlide: "이전 슬라이드", nextSlide: "다음 슬라이드",
    slideOf: (i, n) => `${n}중 ${i}`, offerEnded: "이 혜택은 종료되었습니다",
    leaveAComment: "댓글 남기기", commentForms: { other: "개의 댓글" },
    yourName: "이름", yourEmail: "이메일(공개되지 않음)", yourWebsite: "웹사이트(선택)",
    yourComment: "댓글", postComment: "댓글 등록", posting: "등록 중…",
    commentPending: "감사합니다 — 댓글이 전송되었으며 승인 후 표시됩니다.",
    commentPosted: "감사합니다 — 댓글이 등록되었습니다.",
    postsBy: (n) => `${n}님의 글`, siteTeam: "사이트 팀 작성.",
    playVideo: "동영상 재생", playVideoTitled: (t) => `동영상 재생: ${t}`,
    noDateSet: "날짜가 설정되지 않음",
    closedLabel: "휴무", fieldRequired: "{field}은(는) 필수입니다", invalidEmail: "유효한 이메일 주소를 입력하세요",
    sendMessage: "메시지 보내기",
    reply: "답글", cancelReply: "취소",
  },
  vi: {
    search: "Tìm kiếm", searchPlaceholder: "Tìm kiếm…", openSearch: "Mở tìm kiếm",
    closeSearch: "Đóng tìm kiếm",
    searchResultsFor: (q) => `Kết quả tìm kiếm cho “${q}”`,
    noResults: "Không có kết quả nào khớp với tìm kiếm đó.",
    openMenu: "Mở menu", menu: "Menu", closeMenu: "Đóng menu", language: "Ngôn ngữ",
    backToTop: "Lên đầu trang", toggleDarkMode: "Bật/tắt chế độ tối",
    toggleToc: "Hiện hoặc ẩn mục lục", close: "Đóng", map: "Bản đồ",
    carousel: "băng chuyền", slide: "trang chiếu", prevSlide: "Trang chiếu trước", nextSlide: "Trang chiếu sau",
    slideOf: (i, n) => `${i} trên ${n}`, offerEnded: "Ưu đãi này đã kết thúc",
    leaveAComment: "Để lại bình luận", commentForms: { other: "bình luận" },
    yourName: "Tên", yourEmail: "Email (không được đăng)", yourWebsite: "Trang web (tùy chọn)",
    yourComment: "Bình luận của bạn", postComment: "Gửi bình luận", posting: "Đang gửi…",
    commentPending: "Cảm ơn — bình luận của bạn đã được gửi và sẽ hiển thị sau khi được duyệt.",
    commentPosted: "Cảm ơn — bình luận của bạn đã được đăng.",
    postsBy: (n) => `Bài viết của ${n}`, siteTeam: "Viết bởi đội ngũ của trang.",
    playVideo: "Phát video", playVideoTitled: (t) => `Phát video: ${t}`,
    noDateSet: "Chưa đặt ngày",
    closedLabel: "Đóng cửa", fieldRequired: "{field} là bắt buộc", invalidEmail: "Nhập địa chỉ email hợp lệ",
    sendMessage: "Gửi tin nhắn",
    reply: "Trả lời", cancelReply: "Hủy",
  },
  th: {
    search: "ค้นหา", searchPlaceholder: "ค้นหา…", openSearch: "เปิดการค้นหา",
    closeSearch: "ปิดการค้นหา",
    searchResultsFor: (q) => `ผลการค้นหาสำหรับ “${q}”`,
    noResults: "ไม่พบสิ่งที่ตรงกับการค้นหานี้",
    openMenu: "เปิดเมนู", menu: "เมนู", closeMenu: "ปิดเมนู", language: "ภาษา",
    backToTop: "กลับไปด้านบน", toggleDarkMode: "สลับโหมดมืด",
    toggleToc: "แสดงหรือซ่อนสารบัญ", close: "ปิด", map: "แผนที่",
    carousel: "ภาพหมุน", slide: "สไลด์", prevSlide: "สไลด์ก่อนหน้า", nextSlide: "สไลด์ถัดไป",
    slideOf: (i, n) => `${i} จาก ${n}`, offerEnded: "ข้อเสนอนี้สิ้นสุดแล้ว",
    leaveAComment: "แสดงความคิดเห็น", commentForms: { other: "ความคิดเห็น" },
    yourName: "ชื่อ", yourEmail: "อีเมล (ไม่เผยแพร่)", yourWebsite: "เว็บไซต์ (ไม่บังคับ)",
    yourComment: "ความคิดเห็นของคุณ", postComment: "ส่งความคิดเห็น", posting: "กำลังส่ง…",
    commentPending: "ขอบคุณ — ส่งความคิดเห็นแล้ว จะแสดงเมื่อได้รับการอนุมัติ",
    commentPosted: "ขอบคุณ — เผยแพร่ความคิดเห็นของคุณแล้ว",
    postsBy: (n) => `บทความโดย ${n}`, siteTeam: "เขียนโดยทีมงานของเว็บไซต์",
    playVideo: "เล่นวิดีโอ", playVideoTitled: (t) => `เล่นวิดีโอ: ${t}`,
    noDateSet: "ยังไม่ได้ตั้งวันที่",
    closedLabel: "ปิด", fieldRequired: "ต้องระบุ {field}", invalidEmail: "กรุณากรอกอีเมลที่ถูกต้อง",
    sendMessage: "ส่งข้อความ",
    reply: "ตอบกลับ", cancelReply: "ยกเลิก",
  },
  ms: {
    search: "Cari", searchPlaceholder: "Cari…", openSearch: "Buka carian",
    closeSearch: "Tutup carian",
    searchResultsFor: (q) => `Hasil carian untuk “${q}”`,
    noResults: "Tiada apa-apa yang sepadan dengan carian itu.",
    openMenu: "Buka menu", menu: "Menu", closeMenu: "Tutup menu", language: "Bahasa",
    backToTop: "Kembali ke atas", toggleDarkMode: "Tukar mod gelap",
    toggleToc: "Tunjuk atau sembunyikan kandungan", close: "Tutup", map: "Peta",
    carousel: "karusel", slide: "slaid", prevSlide: "Slaid sebelumnya", nextSlide: "Slaid seterusnya",
    slideOf: (i, n) => `${i} daripada ${n}`, offerEnded: "Tawaran ini telah tamat",
    leaveAComment: "Tinggalkan komen", commentForms: { other: "komen" },
    yourName: "Nama", yourEmail: "E-mel (tidak diterbitkan)", yourWebsite: "Laman web (pilihan)",
    yourComment: "Komen anda", postComment: "Hantar komen", posting: "Menghantar…",
    commentPending: "Terima kasih — komen anda telah dihantar dan akan dipaparkan setelah diluluskan.",
    commentPosted: "Terima kasih — komen anda telah diterbitkan.",
    postsBy: (n) => `Artikel oleh ${n}`, siteTeam: "Ditulis oleh pasukan laman ini.",
    playVideo: "Mainkan video", playVideoTitled: (t) => `Mainkan video: ${t}`,
    noDateSet: "Tiada tarikh ditetapkan",
    closedLabel: "Tutup", fieldRequired: "{field} diperlukan", invalidEmail: "Masukkan alamat e-mel yang sah",
    sendMessage: "Hantar mesej",
    reply: "Balas", cancelReply: "Batal",
  },
  fil: {
    search: "Maghanap", searchPlaceholder: "Maghanap…", openSearch: "Buksan ang paghahanap",
    closeSearch: "Isara ang paghahanap",
    searchResultsFor: (q) => `Mga resulta para sa “${q}”`,
    noResults: "Walang tumugma sa paghahanap na iyon.",
    openMenu: "Buksan ang menu", menu: "Menu", closeMenu: "Isara ang menu", language: "Wika",
    backToTop: "Balik sa itaas", toggleDarkMode: "I-toggle ang dark mode",
    toggleToc: "Ipakita o itago ang talaan ng nilalaman", close: "Isara", map: "Mapa",
    carousel: "carousel", slide: "slide", prevSlide: "Nakaraang slide", nextSlide: "Susunod na slide",
    slideOf: (i, n) => `${i} ng ${n}`, offerEnded: "Tapos na ang alok na ito",
    leaveAComment: "Mag-iwan ng komento", commentForms: { one: "komento", other: "na komento" },
    yourName: "Pangalan", yourEmail: "Email (hindi ilalathala)", yourWebsite: "Website (opsyonal)",
    yourComment: "Ang iyong komento", postComment: "Ipadala ang komento", posting: "Ipinapadala…",
    commentPending: "Salamat — naipadala ang iyong komento at lalabas kapag naaprubahan na.",
    commentPosted: "Salamat — nailathala na ang iyong komento.",
    postsBy: (n) => `Mga post ni ${n}`, siteTeam: "Isinulat ng koponan ng site.",
    playVideo: "I-play ang video", playVideoTitled: (t) => `I-play ang video: ${t}`,
    noDateSet: "Walang nakatakdang petsa",
    closedLabel: "Sarado", fieldRequired: "Kailangan ang {field}", invalidEmail: "Maglagay ng wastong email address",
    sendMessage: "Ipadala ang mensahe",
    reply: "Tumugon", cancelReply: "Kanselahin",
  },
  sw: {
    search: "Tafuta", searchPlaceholder: "Tafuta…", openSearch: "Fungua utafutaji",
    closeSearch: "Funga utafutaji",
    searchResultsFor: (q) => `Matokeo ya utafutaji wa “${q}”`,
    noResults: "Hakuna kilicholingana na utafutaji huo.",
    openMenu: "Fungua menyu", menu: "Menyu", closeMenu: "Funga menyu", language: "Lugha",
    backToTop: "Rudi juu", toggleDarkMode: "Badilisha hali ya giza",
    toggleToc: "Onyesha au ficha yaliyomo", close: "Funga", map: "Ramani",
    carousel: "kanda", slide: "slaidi", prevSlide: "Slaidi iliyotangulia", nextSlide: "Slaidi inayofuata",
    slideOf: (i, n) => `${i} kati ya ${n}`, offerEnded: "Ofa hii imekwisha",
    leaveAComment: "Acha maoni", commentForms: { one: "maoni", other: "maoni" },
    yourName: "Jina", yourEmail: "Barua pepe (haitachapishwa)", yourWebsite: "Tovuti (si lazima)",
    yourComment: "Maoni yako", postComment: "Tuma maoni", posting: "Inatuma…",
    commentPending: "Asante — maoni yako yametumwa na yataonekana yakishaidhinishwa.",
    commentPosted: "Asante — maoni yako yamechapishwa.",
    postsBy: (n) => `Machapisho ya ${n}`, siteTeam: "Imeandikwa na timu ya tovuti.",
    playVideo: "Cheza video", playVideoTitled: (t) => `Cheza video: ${t}`,
    noDateSet: "Hakuna tarehe iliyowekwa",
    closedLabel: "Imefungwa", fieldRequired: "{field} inahitajika", invalidEmail: "Weka anwani sahihi ya barua pepe",
    sendMessage: "Tuma ujumbe",
    reply: "Jibu", cancelReply: "Ghairi",
  },
  bn: {
    search: "খুঁজুন", searchPlaceholder: "খুঁজুন…", openSearch: "অনুসন্ধান খুলুন",
    closeSearch: "অনুসন্ধান বন্ধ করুন",
    searchResultsFor: (q) => `“${q}”-এর অনুসন্ধান ফলাফল`,
    noResults: "এই অনুসন্ধানে কিছু মেলেনি।",
    openMenu: "মেনু খুলুন", menu: "মেনু", closeMenu: "মেনু বন্ধ করুন", language: "ভাষা",
    backToTop: "উপরে ফিরুন", toggleDarkMode: "ডার্ক মোড বদলান",
    toggleToc: "সূচিপত্র দেখান বা লুকান", close: "বন্ধ", map: "মানচিত্র",
    carousel: "ক্যারুসেল", slide: "স্লাইড", prevSlide: "পূর্ববর্তী স্লাইড", nextSlide: "পরবর্তী স্লাইড",
    slideOf: (i, n) => `${n}-এর মধ্যে ${i}`, offerEnded: "এই অফারটি শেষ হয়েছে",
    leaveAComment: "একটি মন্তব্য করুন", commentForms: { one: "টি মন্তব্য", other: "টি মন্তব্য" },
    yourName: "নাম", yourEmail: "ইমেইল (প্রকাশ করা হবে না)", yourWebsite: "ওয়েবসাইট (ऐচ্ছিক)",
    yourComment: "আপনার মন্তব্য", postComment: "মন্তব্য পাঠান", posting: "পাঠানো হচ্ছে…",
    commentPending: "ধন্যবাদ — আপনার মন্তব্য পাঠানো হয়েছে, অনুমোদনের পর দেখা যাবে।",
    commentPosted: "ধন্যবাদ — আপনার মন্তব্য প্রকাশিত হয়েছে।",
    postsBy: (n) => `${n}-এর পোস্ট`, siteTeam: "সাইট দলের লেখা।",
    playVideo: "ভিডিও চালান", playVideoTitled: (t) => `ভিডিও চালান: ${t}`,
    noDateSet: "কোনো তারিখ নির্ধারিত নেই",
    closedLabel: "বন্ধ", fieldRequired: "{field} আবশ্যক", invalidEmail: "একটি বৈধ ইমেল ঠিকানা লিখুন",
    sendMessage: "বার্তা পাঠান",
    reply: "উত্তর দিন", cancelReply: "বাতিল",
  },
  ps: {
    search: "لټون", searchPlaceholder: "لټون…", openSearch: "لټون پرانیزئ", closeSearch: "لټون وتړئ",
    searchResultsFor: (q) => `د «${q}» لپاره د لټون پایلې`, noResults: "د دې لټون لپاره هېڅ ونه موندل شول.",
    openMenu: "مینو پرانیزئ", menu: "مینو", closeMenu: "مینو وتړئ", language: "ژبه",
    backToTop: "پورته ته ستنېدل", toggleDarkMode: "تیاره حالت بدل کړئ",
    toggleToc: "د منځپانګې لړلیک ښکاره یا پټ کړئ", close: "تړل", map: "نقشه", carousel: "کاروسل",
    slide: "سلایډ", prevSlide: "مخکینی سلایډ", nextSlide: "بل سلایډ", slideOf: (i, n) => `${i} له ${n}`,
    offerEnded: "دا وړاندیز پای ته رسېدلی", leaveAComment: "تبصره وکړئ",
    commentForms: { one: "تبصره", other: "تبصرې" }, yourName: "نوم", yourEmail: "برېښنالیک (نه خپرېږي)",
    yourWebsite: "وېبپاڼه (اختیاري)", yourComment: "ستاسو تبصره", postComment: "تبصره واستوئ",
    posting: "استول کېږي…", commentPending: "مننه — ستاسو تبصره واستول شوه او له تایید وروسته به ښکاره شي.",
    commentPosted: "مننه — ستاسو تبصره خپره شوه.", postsBy: (n) => `د ${n} لیکنې`,
    siteTeam: "د سایټ ټیم لیکلی.", playVideo: "ویډیو وچلوئ", playVideoTitled: (t) => `ویډیو وچلوئ: ${t}`,
    noDateSet: "نېټه نه ده ټاکل شوې", closedLabel: "تړلی", fieldRequired: "{field} اړین دی",
    invalidEmail: "یو سم برېښنالیک پته ولیکئ", sendMessage: "پیغام واستوئ", reply: "ځواب", cancelReply: "لغوه",
  },
  pa: {
    search: "ਖੋਜੋ", searchPlaceholder: "ਖੋਜੋ…", openSearch: "ਖੋਜ ਖੋਲ੍ਹੋ", closeSearch: "ਖੋਜ ਬੰਦ ਕਰੋ",
    searchResultsFor: (q) => `“${q}” ਲਈ ਖੋਜ ਨਤੀਜੇ`, noResults: "ਇਸ ਖੋਜ ਨਾਲ ਕੁਝ ਵੀ ਮੇਲ ਨਹੀਂ ਖਾਂਦਾ।",
    openMenu: "ਮੀਨੂ ਖੋਲ੍ਹੋ", menu: "ਮੀਨੂ", closeMenu: "ਮੀਨੂ ਬੰਦ ਕਰੋ", language: "ਭਾਸ਼ਾ", backToTop: "ਉੱਪਰ ਜਾਓ",
    toggleDarkMode: "ਡਾਰਕ ਮੋਡ ਬਦਲੋ", toggleToc: "ਸਮੱਗਰੀ ਸੂਚੀ ਦਿਖਾਓ ਜਾਂ ਲੁਕਾਓ", close: "ਬੰਦ ਕਰੋ", map: "ਨਕਸ਼ਾ",
    carousel: "ਕੈਰੋਸਲ", slide: "ਸਲਾਈਡ", prevSlide: "ਪਿਛਲੀ ਸਲਾਈਡ", nextSlide: "ਅਗਲੀ ਸਲਾਈਡ",
    slideOf: (i, n) => `${n} ਵਿੱਚੋਂ ${i}`, offerEnded: "ਇਹ ਪੇਸ਼ਕਸ਼ ਖਤਮ ਹੋ ਗਈ ਹੈ", leaveAComment: "ਟਿੱਪਣੀ ਕਰੋ",
    commentForms: { one: "ਟਿੱਪਣੀ", other: "ਟਿੱਪਣੀਆਂ" }, yourName: "ਨਾਮ",
    yourEmail: "ਈਮੇਲ (ਪ੍ਰਕਾਸ਼ਿਤ ਨਹੀਂ ਹੋਵੇਗੀ)", yourWebsite: "ਵੈੱਬਸਾਈਟ (ਵਿਕਲਪਿਕ)", yourComment: "ਤੁਹਾਡੀ ਟਿੱਪਣੀ",
    postComment: "ਟਿੱਪਣੀ ਭੇਜੋ", posting: "ਭੇਜੀ ਜਾ ਰਹੀ ਹੈ…",
    commentPending: "ਧੰਨਵਾਦ — ਤੁਹਾਡੀ ਟਿੱਪਣੀ ਭੇਜ ਦਿੱਤੀ ਗਈ ਹੈ ਅਤੇ ਮਨਜ਼ੂਰੀ ਤੋਂ ਬਾਅਦ ਦਿਖਾਈ ਦੇਵੇਗੀ।",
    commentPosted: "ਧੰਨਵਾਦ — ਤੁਹਾਡੀ ਟਿੱਪਣੀ ਪ੍ਰਕਾਸ਼ਿਤ ਹੋ ਗਈ ਹੈ।", postsBy: (n) => `${n} ਦੀਆਂ ਪੋਸਟਾਂ`,
    siteTeam: "ਸਾਈਟ ਟੀਮ ਵੱਲੋਂ ਲਿਖਿਆ ਗਿਆ।", playVideo: "ਵੀਡੀਓ ਚਲਾਓ", playVideoTitled: (t) => `ਵੀਡੀਓ ਚਲਾਓ: ${t}`,
    noDateSet: "ਕੋਈ ਮਿਤੀ ਤੈਅ ਨਹੀਂ", closedLabel: "ਬੰਦ", fieldRequired: "{field} ਲੋੜੀਂਦਾ ਹੈ",
    invalidEmail: "ਇੱਕ ਸਹੀ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ", sendMessage: "ਸੁਨੇਹਾ ਭੇਜੋ", reply: "ਜਵਾਬ ਦਿਓ",
    cancelReply: "ਰੱਦ ਕਰੋ",
  },
  ta: {
    search: "தேடு", searchPlaceholder: "தேடு…", openSearch: "தேடலைத் திற", closeSearch: "தேடலை மூடு",
    searchResultsFor: (q) => `“${q}” க்கான தேடல் முடிவுகள்`,
    noResults: "இந்தத் தேடலுக்கு எதுவும் பொருந்தவில்லை.", openMenu: "மெனுவைத் திற", menu: "மெனு",
    closeMenu: "மெனுவை மூடு", language: "மொழி", backToTop: "மேலே செல்",
    toggleDarkMode: "இருண்ட பயன்முறையை மாற்று", toggleToc: "உள்ளடக்க அட்டவணையைக் காட்டு அல்லது மறை",
    close: "மூடு", map: "வரைபடம்", carousel: "கரோசல்", slide: "ஸ்லைடு", prevSlide: "முந்தைய ஸ்லைடு",
    nextSlide: "அடுத்த ஸ்லைடு", slideOf: (i, n) => `${n} இல் ${i}`, offerEnded: "இந்தச் சலுகை முடிந்துவிட்டது",
    leaveAComment: "கருத்து தெரிவிக்கவும்", commentForms: { one: "கருத்து", other: "கருத்துகள்" },
    yourName: "பெயர்", yourEmail: "மின்னஞ்சல் (வெளியிடப்படாது)", yourWebsite: "இணையதளம் (விருப்பத்தேர்வு)",
    yourComment: "உங்கள் கருத்து", postComment: "கருத்தை அனுப்பு", posting: "அனுப்பப்படுகிறது…",
    commentPending: "நன்றி — உங்கள் கருத்து அனுப்பப்பட்டது, ஒப்புதலுக்குப் பிறகு தோன்றும்.",
    commentPosted: "நன்றி — உங்கள் கருத்து வெளியிடப்பட்டது.", postsBy: (n) => `${n} எழுதிய பதிவுகள்`,
    siteTeam: "தளக் குழுவால் எழுதப்பட்டது.", playVideo: "வீடியோவை இயக்கு",
    playVideoTitled: (t) => `வீடியோவை இயக்கு: ${t}`, noDateSet: "தேதி அமைக்கப்படவில்லை",
    closedLabel: "மூடப்பட்டது", fieldRequired: "{field} தேவை",
    invalidEmail: "சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்", sendMessage: "செய்தி அனுப்பு", reply: "பதில்",
    cancelReply: "ரத்துசெய்",
  },
  te: {
    search: "వెతకండి", searchPlaceholder: "వెతకండి…", openSearch: "శోధనను తెరవండి",
    closeSearch: "శోధనను మూసివేయండి", searchResultsFor: (q) => `“${q}” కోసం శోధన ఫలితాలు`,
    noResults: "ఈ శోధనకు ఏదీ సరిపోలలేదు.", openMenu: "మెనూ తెరవండి", menu: "మెనూ", closeMenu: "మెనూ మూసివేయండి",
    language: "భాష", backToTop: "పైకి వెళ్ళండి", toggleDarkMode: "డార్క్ మోడ్ మార్చండి",
    toggleToc: "విషయ సూచికను చూపించు లేదా దాచు", close: "మూసివేయి", map: "మ్యాప్", carousel: "కారసెల్",
    slide: "స్లైడ్", prevSlide: "మునుపటి స్లైడ్", nextSlide: "తదుపరి స్లైడ్", slideOf: (i, n) => `${n}లో ${i}`,
    offerEnded: "ఈ ఆఫర్ ముగిసింది", leaveAComment: "వ్యాఖ్యానించండి",
    commentForms: { one: "వ్యాఖ్య", other: "వ్యాఖ్యలు" }, yourName: "పేరు",
    yourEmail: "ఇమెయిల్ (ప్రచురించబడదు)", yourWebsite: "వెబ్‌సైట్ (ఐచ్ఛికం)", yourComment: "మీ వ్యాఖ్య",
    postComment: "వ్యాఖ్యను పంపండి", posting: "పంపుతోంది…",
    commentPending: "ధన్యవాదాలు — మీ వ్యాఖ్య పంపబడింది, ఆమోదం తర్వాత కనిపిస్తుంది.",
    commentPosted: "ధన్యవాదాలు — మీ వ్యాఖ్య ప్రచురించబడింది.", postsBy: (n) => `${n} రాసిన పోస్ట్‌లు`,
    siteTeam: "సైట్ బృందం రాసినది.", playVideo: "వీడియో ప్లే చేయండి",
    playVideoTitled: (t) => `వీడియో ప్లే చేయండి: ${t}`, noDateSet: "తేదీ సెట్ చేయలేదు",
    closedLabel: "మూసివేయబడింది", fieldRequired: "{field} తప్పనిసరి",
    invalidEmail: "సరైన ఇమెయిల్ చిరునామాను నమోదు చేయండి", sendMessage: "సందేశం పంపండి", reply: "ప్రత్యుత్తరం",
    cancelReply: "రద్దు చేయి",
  },
  mr: {
    search: "शोधा", searchPlaceholder: "शोधा…", openSearch: "शोध उघडा", closeSearch: "शोध बंद करा",
    searchResultsFor: (q) => `“${q}” साठी शोध परिणाम`, noResults: "या शोधाशी काहीही जुळले नाही.",
    openMenu: "मेनू उघडा", menu: "मेनू", closeMenu: "मेनू बंद करा", language: "भाषा", backToTop: "वर जा",
    toggleDarkMode: "डार्क मोड बदला", toggleToc: "अनुक्रमणिका दाखवा किंवा लपवा", close: "बंद करा", map: "नकाशा",
    carousel: "कॅरोसेल", slide: "स्लाइड", prevSlide: "मागील स्लाइड", nextSlide: "पुढील स्लाइड",
    slideOf: (i, n) => `${n} पैकी ${i}`, offerEnded: "ही ऑफर संपली आहे", leaveAComment: "प्रतिक्रिया द्या",
    commentForms: { one: "प्रतिक्रिया", other: "प्रतिक्रिया" }, yourName: "नाव",
    yourEmail: "ईमेल (प्रकाशित केला जाणार नाही)", yourWebsite: "वेबसाइट (पर्यायी)",
    yourComment: "तुमची प्रतिक्रिया", postComment: "प्रतिक्रिया पाठवा", posting: "पाठवत आहे…",
    commentPending: "धन्यवाद — तुमची प्रतिक्रिया पाठवली आहे आणि मंजुरीनंतर दिसेल.",
    commentPosted: "धन्यवाद — तुमची प्रतिक्रिया प्रकाशित झाली आहे.", postsBy: (n) => `${n} यांचे लेख`,
    siteTeam: "साइट टीमने लिहिलेले.", playVideo: "व्हिडिओ चालवा", playVideoTitled: (t) => `व्हिडिओ चालवा: ${t}`,
    noDateSet: "तारीख ठरवलेली नाही", closedLabel: "बंद", fieldRequired: "{field} आवश्यक आहे",
    invalidEmail: "वैध ईमेल पत्ता टाका", sendMessage: "संदेश पाठवा", reply: "उत्तर द्या",
    cancelReply: "रद्द करा",
  },
  gu: {
    search: "શોધો", searchPlaceholder: "શોધો…", openSearch: "શોધ ખોલો", closeSearch: "શોધ બંધ કરો",
    searchResultsFor: (q) => `“${q}” માટે શોધ પરિણામો`, noResults: "આ શોધ સાથે કંઈ મેળ ખાતું નથી.",
    openMenu: "મેનૂ ખોલો", menu: "મેનૂ", closeMenu: "મેનૂ બંધ કરો", language: "ભાષા", backToTop: "ઉપર જાઓ",
    toggleDarkMode: "ડાર્ક મોડ બદલો", toggleToc: "અનુક્રમણિકા બતાવો અથવા છુપાવો", close: "બંધ કરો", map: "નકશો",
    carousel: "કેરોસેલ", slide: "સ્લાઇડ", prevSlide: "પાછલી સ્લાઇડ", nextSlide: "આગલી સ્લાઇડ",
    slideOf: (i, n) => `${n} માંથી ${i}`, offerEnded: "આ ઑફર પૂરી થઈ ગઈ છે", leaveAComment: "ટિપ્પણી કરો",
    commentForms: { one: "ટિપ્પણી", other: "ટિપ્પણીઓ" }, yourName: "નામ",
    yourEmail: "ઇમેઇલ (પ્રકાશિત નહીં થાય)", yourWebsite: "વેબસાઇટ (વૈકલ્પિક)", yourComment: "તમારી ટિપ્પણી",
    postComment: "ટિપ્પણી મોકલો", posting: "મોકલી રહ્યા છીએ…",
    commentPending: "આભાર — તમારી ટિપ્પણી મોકલવામાં આવી છે અને મંજૂરી પછી દેખાશે.",
    commentPosted: "આભાર — તમારી ટિપ્પણી પ્રકાશિત થઈ ગઈ છે.", postsBy: (n) => `${n} ની પોસ્ટ્સ`,
    siteTeam: "સાઇટ ટીમ દ્વારા લખાયેલું.", playVideo: "વિડિયો ચલાવો",
    playVideoTitled: (t) => `વિડિયો ચલાવો: ${t}`, noDateSet: "કોઈ તારીખ નક્કી નથી", closedLabel: "બંધ",
    fieldRequired: "{field} જરૂરી છે", invalidEmail: "માન્ય ઇમેઇલ સરનામું દાખલ કરો", sendMessage: "સંદેશ મોકલો",
    reply: "જવાબ આપો", cancelReply: "રદ કરો",
  },
  kn: {
    search: "ಹುಡುಕಿ", searchPlaceholder: "ಹುಡುಕಿ…", openSearch: "ಹುಡುಕಾಟ ತೆರೆಯಿರಿ",
    closeSearch: "ಹುಡುಕಾಟ ಮುಚ್ಚಿ", searchResultsFor: (q) => `“${q}” ಗಾಗಿ ಹುಡುಕಾಟದ ಫಲಿತಾಂಶಗಳು`,
    noResults: "ಈ ಹುಡುಕಾಟಕ್ಕೆ ಏನೂ ಹೊಂದಿಕೆಯಾಗಲಿಲ್ಲ.", openMenu: "ಮೆನು ತೆರೆಯಿರಿ", menu: "ಮೆನು",
    closeMenu: "ಮೆನು ಮುಚ್ಚಿ", language: "ಭಾಷೆ", backToTop: "ಮೇಲಕ್ಕೆ ಹೋಗಿ", toggleDarkMode: "ಡಾರ್ಕ್ ಮೋಡ್ ಬದಲಿಸಿ",
    toggleToc: "ವಿಷಯಸೂಚಿ ತೋರಿಸಿ ಅಥವಾ ಮರೆಮಾಡಿ", close: "ಮುಚ್ಚಿ", map: "ನಕ್ಷೆ", carousel: "ಕ್ಯಾರೋಸೆಲ್",
    slide: "ಸ್ಲೈಡ್", prevSlide: "ಹಿಂದಿನ ಸ್ಲೈಡ್", nextSlide: "ಮುಂದಿನ ಸ್ಲೈಡ್",
    slideOf: (i, n) => `${n} ರಲ್ಲಿ ${i}`, offerEnded: "ಈ ಕೊಡುಗೆ ಮುಗಿದಿದೆ", leaveAComment: "ಪ್ರತಿಕ್ರಿಯೆ ನೀಡಿ",
    commentForms: { one: "ಪ್ರತಿಕ್ರಿಯೆ", other: "ಪ್ರತಿಕ್ರಿಯೆಗಳು" }, yourName: "ಹೆಸರು",
    yourEmail: "ಇಮೇಲ್ (ಪ್ರಕಟಿಸಲಾಗುವುದಿಲ್ಲ)", yourWebsite: "ವೆಬ್‌ಸೈಟ್ (ಐಚ್ಛಿಕ)",
    yourComment: "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ", postComment: "ಪ್ರತಿಕ್ರಿಯೆ ಕಳುಹಿಸಿ", posting: "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…",
    commentPending: "ಧನ್ಯವಾದಗಳು — ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ ಕಳುಹಿಸಲಾಗಿದೆ, ಅನುಮೋದನೆಯ ನಂತರ ಕಾಣಿಸುತ್ತದೆ.",
    commentPosted: "ಧನ್ಯವಾದಗಳು — ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ ಪ್ರಕಟವಾಗಿದೆ.", postsBy: (n) => `${n} ಅವರ ಲೇಖನಗಳು`,
    siteTeam: "ಸೈಟ್ ತಂಡದಿಂದ ಬರೆಯಲಾಗಿದೆ.", playVideo: "ವೀಡಿಯೊ ಪ್ಲೇ ಮಾಡಿ",
    playVideoTitled: (t) => `ವೀಡಿಯೊ ಪ್ಲೇ ಮಾಡಿ: ${t}`, noDateSet: "ದಿನಾಂಕ ನಿಗದಿಪಡಿಸಿಲ್ಲ",
    closedLabel: "ಮುಚ್ಚಲಾಗಿದೆ", fieldRequired: "{field} ಅಗತ್ಯವಿದೆ",
    invalidEmail: "ಮಾನ್ಯವಾದ ಇಮೇಲ್ ವಿಳಾಸ ನಮೂದಿಸಿ", sendMessage: "ಸಂದೇಶ ಕಳುಹಿಸಿ", reply: "ಉತ್ತರಿಸಿ",
    cancelReply: "ರದ್ದುಮಾಡಿ",
  },
  ml: {
    search: "തിരയുക", searchPlaceholder: "തിരയുക…", openSearch: "തിരയൽ തുറക്കുക",
    closeSearch: "തിരയൽ അടയ്ക്കുക", searchResultsFor: (q) => `“${q}” എന്നതിനുള്ള തിരയൽ ഫലങ്ങൾ`,
    noResults: "ഈ തിരയലുമായി ഒന്നും പൊരുത്തപ്പെട്ടില്ല.", openMenu: "മെനു തുറക്കുക", menu: "മെനു",
    closeMenu: "മെനു അടയ്ക്കുക", language: "ഭാഷ", backToTop: "മുകളിലേക്ക് പോകുക",
    toggleDarkMode: "ഡാർക്ക് മോഡ് മാറ്റുക", toggleToc: "ഉള്ളടക്കപ്പട്ടിക കാണിക്കുക അല്ലെങ്കിൽ മറയ്ക്കുക",
    close: "അടയ്ക്കുക", map: "മാപ്പ്", carousel: "കറൗസൽ", slide: "സ്ലൈഡ്", prevSlide: "മുമ്പത്തെ സ്ലൈഡ്",
    nextSlide: "അടുത്ത സ്ലൈഡ്", slideOf: (i, n) => `${n}-ൽ ${i}`, offerEnded: "ഈ ഓഫർ അവസാനിച്ചു",
    leaveAComment: "അഭിപ്രായം രേഖപ്പെടുത്തുക", commentForms: { one: "അഭിപ്രായം", other: "അഭിപ്രായങ്ങൾ" },
    yourName: "പേര്", yourEmail: "ഇമെയിൽ (പ്രസിദ്ധീകരിക്കില്ല)", yourWebsite: "വെബ്സൈറ്റ് (ഐച്ഛികം)",
    yourComment: "നിങ്ങളുടെ അഭിപ്രായം", postComment: "അഭിപ്രായം അയയ്ക്കുക", posting: "അയയ്ക്കുന്നു…",
    commentPending: "നന്ദി — നിങ്ങളുടെ അഭിപ്രായം അയച്ചു, അംഗീകാരത്തിന് ശേഷം ദൃശ്യമാകും.",
    commentPosted: "നന്ദി — നിങ്ങളുടെ അഭിപ്രായം പ്രസിദ്ധീകരിച്ചു.", postsBy: (n) => `${n} എഴുതിയ പോസ്റ്റുകൾ`,
    siteTeam: "സൈറ്റ് ടീം എഴുതിയത്.", playVideo: "വീഡിയോ പ്ലേ ചെയ്യുക",
    playVideoTitled: (t) => `വീഡിയോ പ്ലേ ചെയ്യുക: ${t}`, noDateSet: "തീയതി നിശ്ചയിച്ചിട്ടില്ല",
    closedLabel: "അടച്ചിരിക്കുന്നു", fieldRequired: "{field} ആവശ്യമാണ്",
    invalidEmail: "സാധുവായ ഇമെയിൽ വിലാസം നൽകുക", sendMessage: "സന്ദേശം അയയ്ക്കുക", reply: "മറുപടി",
    cancelReply: "റദ്ദാക്കുക",
  },
  ne: {
    search: "खोज्नुहोस्", searchPlaceholder: "खोज्नुहोस्…", openSearch: "खोज खोल्नुहोस्",
    closeSearch: "खोज बन्द गर्नुहोस्", searchResultsFor: (q) => `“${q}” का लागि खोज नतिजा`,
    noResults: "यो खोजसँग केही मिलेन।", openMenu: "मेनु खोल्नुहोस्", menu: "मेनु",
    closeMenu: "मेनु बन्द गर्नुहोस्", language: "भाषा", backToTop: "माथि जानुहोस्",
    toggleDarkMode: "डार्क मोड बदल्नुहोस्", toggleToc: "विषयसूची देखाउनुहोस् वा लुकाउनुहोस्",
    close: "बन्द गर्नुहोस्", map: "नक्सा", carousel: "क्यारोसेल", slide: "स्लाइड", prevSlide: "अघिल्लो स्लाइड",
    nextSlide: "अर्को स्लाइड", slideOf: (i, n) => `${n} मध्ये ${i}`, offerEnded: "यो प्रस्ताव समाप्त भएको छ",
    leaveAComment: "टिप्पणी गर्नुहोस्", commentForms: { one: "टिप्पणी", other: "टिप्पणीहरू" }, yourName: "नाम",
    yourEmail: "इमेल (प्रकाशित गरिने छैन)", yourWebsite: "वेबसाइट (ऐच्छिक)", yourComment: "तपाईंको टिप्पणी",
    postComment: "टिप्पणी पठाउनुहोस्", posting: "पठाउँदै…",
    commentPending: "धन्यवाद — तपाईंको टिप्पणी पठाइएको छ र स्वीकृतिपछि देखिनेछ।",
    commentPosted: "धन्यवाद — तपाईंको टिप्पणी प्रकाशित भयो।", postsBy: (n) => `${n} का लेखहरू`,
    siteTeam: "साइट टोलीद्वारा लेखिएको।", playVideo: "भिडियो चलाउनुहोस्",
    playVideoTitled: (t) => `भिडियो चलाउनुहोस्: ${t}`, noDateSet: "मिति तोकिएको छैन", closedLabel: "बन्द",
    fieldRequired: "{field} आवश्यक छ", invalidEmail: "मान्य इमेल ठेगाना लेख्नुहोस्",
    sendMessage: "सन्देश पठाउनुहोस्", reply: "जवाफ दिनुहोस्", cancelReply: "रद्द गर्नुहोस्",
  },
  si: {
    search: "සොයන්න", searchPlaceholder: "සොයන්න…", openSearch: "සෙවුම විවෘත කරන්න", closeSearch: "සෙවුම වසන්න",
    searchResultsFor: (q) => `“${q}” සඳහා සෙවුම් ප්‍රතිඵල`, noResults: "මෙම සෙවුමට කිසිවක් නොගැළපුණි.",
    openMenu: "මෙනුව විවෘත කරන්න", menu: "මෙනුව", closeMenu: "මෙනුව වසන්න", language: "භාෂාව",
    backToTop: "ඉහළට යන්න", toggleDarkMode: "අඳුරු ප්‍රකාරය මාරු කරන්න", toggleToc: "පටුන පෙන්වන්න හෝ සඟවන්න",
    close: "වසන්න", map: "සිතියම", carousel: "කැරසලය", slide: "ස්ලයිඩය", prevSlide: "පෙර ස්ලයිඩය",
    nextSlide: "ඊළඟ ස්ලයිඩය", slideOf: (i, n) => `${n} න් ${i}`, offerEnded: "මෙම දීමනාව අවසන් වී ඇත",
    leaveAComment: "අදහසක් දක්වන්න", commentForms: { one: "අදහස", other: "අදහස්" }, yourName: "නම",
    yourEmail: "විද්‍යුත් තැපෑල (ප්‍රසිද්ධ නොකෙරේ)", yourWebsite: "වෙබ් අඩවිය (අත්‍යවශ්‍ය නොවේ)",
    yourComment: "ඔබේ අදහස", postComment: "අදහස යවන්න", posting: "යවමින්…",
    commentPending: "ස්තූතියි — ඔබේ අදහස යවා ඇති අතර අනුමත කළ පසු දිස්වනු ඇත.",
    commentPosted: "ස්තූතියි — ඔබේ අදහස පළ කර ඇත.", postsBy: (n) => `${n} ගේ ලිපි`,
    siteTeam: "අඩවි කණ්ඩායම විසින් ලියන ලදී.", playVideo: "වීඩියෝව ධාවනය කරන්න",
    playVideoTitled: (t) => `වීඩියෝව ධාවනය කරන්න: ${t}`, noDateSet: "දිනයක් සකසා නැත", closedLabel: "වසා ඇත",
    fieldRequired: "{field} අවශ්‍යයි", invalidEmail: "වලංගු විද්‍යුත් තැපැල් ලිපිනයක් ඇතුළත් කරන්න",
    sendMessage: "පණිවිඩය යවන්න", reply: "පිළිතුරු දෙන්න", cancelReply: "අවලංගු කරන්න",
  },
};

/** The chrome wording for a language tag (`ar`, `ar-EG`), English when there is none. */
export function uiText(language: string): UiText {
  const base = (language || "").split("-")[0].toLowerCase();
  // Matched key, not the requested one — see archiveText for why.
  const key = TEXT[language] ? language : TEXT[base] ? base : "en";
  const { commentForms, ...rest } = TEXT[key];
  // `lang` is the key that MATCHED, not the one asked for. Anything that
  // formats with `Intl` (weekday names, numbers) must use the same language
  // the surrounding text came from, or an Urdu page falls back to English
  // wording next to Urdu day names.
  return {
    ...rest,
    lang: key,
    comments: (n) => counted(key, n, commentForms),
    skipToContent: SKIP_TO_CONTENT[key] ?? SKIP_TO_CONTENT.en,
    ...(MEDIA_CONTROLS[key] ?? MEDIA_CONTROLS.en),
  };
}
